### ISSUE TITLE
Getting 502 Bad Gateway while having healthy app instances

### ISSUE THREAD

**Issue by renelehmann** [cloudfoundry/routing-release#132] opened 2018-12-04 17:24 UTC
## Issue
If we kill one instance of multiple app instances then we get the response 
`502 Bad Gateway: Registered endpoint failed to handle the request.` 
for about `4-5 seconds` for that particular app .

## Context
Giving an environment with 3 gorouter's. Round-robin/random access.
Secured app traffic (TLS).
Running 3 app instances for the same app on different cells. Accessed randomly.

If one of three instances is not reachable anymore (crashed/killed) then we
get a `502` response for about 4-5 seconds while curl-ing the app endpoint.  
During this time the other healthy app instances responds with the expected result.
This response error has been seen since `routing-release v0.183.0`
Not sure if we get the same result on non TLS activated app traffic (not tested yet).  

## Steps to Reproduce
Running an app with 2 or more instances.
curl-ing the endpoint within a while-loop.
ssh into one app instance and killing the main process.

## Expected result
To see no `502` error on the client side since the "app" has at least one healthy app instance.

## Current result
`502 Bad Gateway: Registered endpoint failed to handle the request.` (for about 4-5 seconds)

Example: 
The main process on app instance index 1 was killed while hitting the "app"-endpoint:
`while true; do curl https://app.example.com;done`

```{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:41 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:42 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:42 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:42 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:42 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:43 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:43 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:43 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:43 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:44 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:44 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:44 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:44 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:45 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:45 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:45 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:45 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:46 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:46 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:46 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:46 UTC 2018
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"0"}Fri Nov 30 09:54:47 UTC 2018
502 Bad Gateway: Registered endpoint failed to handle the request.
{"name":"Hans Muster","nationality":"Switzerland","instanceIndex":"2"}Fri Nov 30 09:54:47 UTC 2018
```

After some more seconds the app instance index 1 is fully restarted, back again and responds .

**Comment by shubhaat** [comment] 2018-12-04 21:01
Hi @renelehmann, 

Thanks for creating this in addition to the slack conversation. So we did add the behavior to prune a backend that might be crashing or closing a connection mid request and not retry to a healthy backend in routing-release 0.183.0 with [this story](https://www.pivotaltracker.com/n/projects/1358110/stories/157521684). The reason we decided to prune an unhealthy backend and not retry another healthy instance is to avoid a non-idempotent request from retrying. Given that a request was in progress, depending on how the application has been architected, it is possible that there were changes made that could impact subsequent requests, and we did not want to retry in that case. 

The behavior you are seeing mostly seems in line with this. Can you also give us the Gorouter error logs for when you see the 502s, do you see a `read: connection reset by peer`?

CF Routing team

**Comment by renelehmann** [comment] 2018-12-05 11:46
Hi @shubhaat 

Thanks for looking into that.

I reproduced shorty the scenario.
I did not see any `read: connection reset by peer` on the gorouter logs.

This is how it looks like on the gorouter logs as soon one instance gets killed:
(following logs and grep the ApplicationId)

route-emitter "backend-endpoint-failed":
```
router/3ff2487f-185a-497c-9805-1f77edb2ffea: stdout | {"log_level":3,"timestamp":1544004444.2359376,"message":"backend-endpoint-failed","source":"vcap.gorouter",
"data":{"route-endpoint":{"ApplicationId":"78803cd7-1ddc-44a4-9be4-abe222c236a0","Addr":"100.106.226.34:61032","Tags":{"component":"route-emitter"},"RouteService
Url":""},"error":"EOF","attempt":1,"vcap_request_id":"723960c1-bb21-452b-45af-4b0b70055c3b"}}
```

follwed from a `502`:
```
router/3ff2487f-185a-497c-9805-1f77edb2ffea: stdout | app.example.com - [2018-12-05T10:07:24.229+0000] "GET / HTTP/1.1" 502 0 67 "-" "curl/7.47.0" "100.10
6.132.129:35630" "100.106.226.34:61032" x_forwarded_for:"100.106.192.20, 100.106.132.129" x_forwarded_proto:"https" vcap_request_id:"723960c1-bb21-452b-45af-4b0b
70055c3b" response_time:0.006646797 app_id:"78803cd7-1ddc-44a4-9be4-abe222c236a0" app_index:"0"
``` 

Above will be repeated on different gorouter's and for the killed app instance until all three gorouters gets the unregister at the same time (like that):
```
router/3ff2487f-185a-497c-9805-1f77edb2ffea: stdout | {"log_level":1,"timestamp":1544004449.3636346,"message":"unregister-route","source":"vcap.gorouter.subscrib
er","data":{"message":"{\"host\":\"100.106.226.34\",\"port\":61030,\"tls_port\":61032,\"uris\":[\"app.example.com\"],\"app\":\"78803cd7-1ddc-44a4-9be4-abe
222c236a0\",\"private_instance_id\":\"de4eddd6-033b-47d8-5ce1-05ce\",\"private_instance_index\":\"0\",\"server_cert_domain_san\":\"de4eddd6-033b-47d8-5ce1-05ce\"
,\"tags\":{\"component\":\"route-emitter\"}}"}}
```


Unix timestamp (see diff 5 seconds)
1544004444.2359376 = `2018-12-05T10:07:24`   //route-emitter backend-failed / 502
1544004449.3636346 = `2018-12-05T10:07:29`  //route-emitter unregister

**Comment by renelehmann** [comment] 2018-12-18 08:19
could you already look at this @shubhaat? Do you need further information from our side to reproduce this? Also happy to chat in Slack if needed. Thanks a lot!

**Comment by utako** [comment] 2018-12-18 21:39
This issue might be related to https://github.com/cloudfoundry/gorouter/issues/219. 

@renelehmann If that other issue appears to be match your problem, I'd prefer to close this issue in favor of the one in gorouter.

**Comment by bruce-ricard** [comment] 2018-12-20 00:19
Hi @renelehmann . We attempted to reproduce the issue. We were able to see similar behavior to the one you described, but the time during which we got the 502 was substantially shorter, ~0.2 seconds. We would be interested in understanding what the differences are between your setup and our which makes for such a difference. 

@nhsieh and I

**Comment by renelehmann** [comment] 2018-12-27 16:40
Hi @bruce-ricard , @nhsieh . Thanks for testing this behaviour.
Additionally to the "Context" described above on this issue and how our setup looks like:
In front of the three gorouter's there is a F5 acting as a load balancer. 
TLS traffic is enabled to the gorouters. 
TLS is activated to securing the app traffic between gorouters and the apps. 
Cloudfoundry is configured like recommended as of cf-deployment (on this env on v6.2.0).
Cloudfoundry is distributed across three datacenters and each instance group consist of at least three vm's. 
The environment consist about 100 cell vms at the moment. 
Nothing special to mention regarding the load or latency to the datacenters.
 

Meanwhile we tested the same versions on another environment with near the same setup 
**but there no TLS is activated** (not on F5/gorouter nor gorouter/apps).
The behaviour doesn't looks the same if we run this test. 
From a client perspective we do not get a `502`. There is **no failure** while curling the app and an app instance got killed/crashed. 
The only thing we noticed is the `connection refused` on the gorouter logs.

We didn't take into account from our last cloudfoundry update (to e.g. routing v0.183.0) we 
additionally **also activated TLS and it was not activated before**.

- From a client perspective why do we have to take notice or to respect **another experience** for that use case and **if TLS is activated or not**?

- As I understand the mechanism of handling unhealthy backends/routes is different with or without TLS.
If the `502` is an expected behaviour, only **while TLS is activated**, what is the **expected amount of time** to receive that error in your opinion?

**Comment by bruce-ricard** [comment] 2019-01-07 18:34
Hi @renelehmann,
Thanks for following up with more context! 

The difference in behavior between TLS and non-TLS was not expected. This might be a bug, we'll look into it.

> what is the expected amount of time to receive that error in your opinion?

We still have a hard time understanding why you get 502's for such a long period of time (5s), that is not expected. The only queries which should return a 502 are the ones that were sent to the failing instance _before_  it failed, and were being processed as it failed. These queries won't be retried and will return a 502 http code. Do your queries typically take 4-5 seconds to get processed on the server by any chance? That would explain why you see errors for that amount of time.

Would you be interested in a quick call with out PM @shubhaat and an engineering pair to answer a few more questions for us? We'd like to discuss expected behavior when apps crash with and without TLS. 
Thanks, 
@bruce-ricard and @tstannard

**Comment by renelehmann** [comment] 2019-01-15 17:15
Hi @bruce-ricard  and @tstannard 

Thanks for your opinion and further statements.
Why we are ending in 4-5 seconds is a good question, but would say that this could be related to the size or pattern of our foundation (cloudfoundry). Not sure about your environment and your test of 0.2 seconds.
The queries doesn't take that long. This 5 seconds are taken from the gorouter log between the message "route-emitter backend-failed" and the message "route-emitter unregister".
See above: https://github.com/cloudfoundry/routing-release/issues/132#issuecomment-444457712

Yes, we could set up a call but I would be more interested on the questions in front of that.
The expected behaviour when apps crashes with or without activated TLS should be the same. 
A customer of a running app with multiple instances should never get a 502 as long one app instance is in a healthy state.

To find a possible date you could contact me on slack (I probably then invite a few additional colleagues on our side): 
https://cloudfoundry.slack.com/team/U4P4EEX88  (renel)

**Comment by nicregez** [comment] 2019-02-06 16:29
This is the app I just showed during our zoom tele conference
https://github.com/nicregez/simple-node

**Comment by renelehmann** [comment] 2019-02-15 14:25
Hi @shubhaat. Are there any news on this topic since the tele conference with @nicregez ?

**Comment by shubhaat** [comment] 2019-02-26 17:52
Hi @nicregez and @renelehmann, Sorry we didn't get back to you sooner. I have been trying to reproduce the scenario Nicolas mentions using the test app but have been running into an [issue](https://github.com/nicregez/simple-node/issues/1). 

Help would be appreciated. My intent is to figure out if this is really a bug or was in someway intended behavior.

**Comment by nicregez** [comment] 2019-02-27 06:56
@shubhaat The reported issue has been solved, please try again

**Comment by ameowlia** [comment] 2019-05-06 17:30
Hi @nicregez, 

It sounds like the problem has been solved. Would you mind sharing how you solved the problem?

Thanks, 
@ameowlia and @bruce-ricard, CF Networking Program Members

**Closed by ameowlia** 2019-05-06 17:30 UTC
Labels: scheduled

**Comment by adobley** [comment] 2019-05-08 17:09
Was that the test app which had an issue solved or the original issue? Sorry about jumping in on the tail end here. It wasn't clear to me and I want to make sure this was right.
