### ISSUE TITLE
Implementing header "Expect: 100-continue" breaks with routing-release >= 0.293.0

### ISSUE THREAD

**Issue by plowin** [cloudfoundry/routing-release#409] opened 2024-05-13 10:51 UTC
### Behavior
If a CF app is implementing the `Expect: 100-continue` header to first read all headers of a request before reading the body, the respective scenario is breaking with routing-release higher than 0.293.0. Previously, the CF app would respond with `201 Created`, whereas this request is responded with `200 ok` [by gorouter](https://github.com/golang/go/blob/master/src/net/http/server.go#L1639) in the new version. 

### Steps to reproduce
* push this simple app that reads the headers (and, as an example, checks the size of content-length before actually reading the request body): https://github.com/plowin/expect-100
* send a request to the /expect handler comparing 0.292.0 and >=0.293.0 and compare the responses, 201 and 200
* `curl` did some magic and the header went missing, but you can see the behavior when e.g. using "bruno":
0.292.0: ![0.292.0](https://github.com/cloudfoundry/routing-release/assets/41676607/35452c84-c538-4128-8465-1ac044b86f1b)
0.296.0: 
![0.296.0](https://github.com/cloudfoundry/routing-release/assets/41676607/561f7859-064b-43dd-9b30-4134ebe32728)

### References
* This seems to be an undesired side-effect of https://github.com/cloudfoundry/gorouter/pull/395.

### Desired behavior

* The default behavior is restored and clients can continue using 100-continue as before
* A test is implemented in routing-release to test the behavior and avoid such regressions in the future

### Affected Version

0.293.0

**Comment by geofffranks** [comment] 2024-05-13 15:59
> Previously, the CF app would respond with 201 continue

Do you mean a 201 created? Also, just so I'm clear - the entire http request/response go through, it's just that the gorouter is changing the status code from 200 to 201, right?

Since the `router.enable_http1_concurrent_read_write` is off by default, were you explictly adding it in 0.293.0 for the test? Did the problem go away on 0.293.0 when EnableFullDuplex is disabled?

In your slack message, you indicated you're seeing this for http2 requests as well - but the code added only affects HTTP 1.1.

Maybe this is a result of migrating to Negroni v3?

**Comment by geofffranks** [comment] 2024-05-13 21:08
We've been able to reproduce this independently with `enable_http1_concurrent_read_write` off. The behavior does indeed go away on 0.292.0. 

It's possible this is Negroni v3, or golang, or one of the many code refactors as a result of staticcheck compliance. We'll do more digging and once we get a better idea of the scope (what status codes get masked, does content size or delay matter, etc), add warnings on release notes.

**Comment by plowin** [comment] 2024-05-14 04:23
Hi @geofffranks, thx `created` ofc - adjusted accordingly.
We also disabled `enable_http1_concurrent_read_write` in our test. Thx for looking into it, ping me on Slack if we can support!

**Comment by maxmoehl** [comment] 2024-05-14 06:41
> Also, just so I'm clear - the entire http request/response go through, it's just that the gorouter is changing the status code from 200 to 201, right?

The other way around: gorouter changes the status code from 201 to 200.

**Comment by geofffranks** [comment] 2024-05-14 15:51
This has been traced back to this negroni commit. https://github.com/urfave/negroni/commit/279b8b01dcee6bd497bdaf19b33c15a12c8b1a81

If I comment out the block that writes the StatusOK header when a header hasn't been written yet, it works as it used to, and none of the gorouter tests fail.

Will need to investigate this more to see if this is the right way to fix it, and PR a fix to negroni.

**Comment by geofffranks** [comment] 2024-05-14 17:57
We tracked it down to [this negroni commit](https://github.com/urfave/negroni/commit/ec1c41c0c3d4d6688ca8dcd45cbb23a1f9e020a8). We have a test for gorouter to validate the scenario, and will work on a PR for negroni that we point gorouter at until it gets merged/released.

**Comment by geofffranks** [comment] 2024-05-14 19:09
https://github.com/urfave/negroni/pull/277

**Closed as completed** 2024-05-14 19:48 UTC
